spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/noveltestdb
  profiles: dev

---
spring:
  datasource:
    username: sa 
    password: 
    url: jdbc:h2:mem:novelhealrhcare
    driver-class-name: org.h2.Driver
  profiles: qa
---
spring:
  profiles:
    active: dev
      
  
    
        